### ISSUE TITLE
При вводе некорректного баланса должно выкидываться исключение 

### ISSUE THREAD

**Issue by Sushnyak** [Sushnyak/commProject#1]
# Описание
При попытке присвоить отрицательный балланс, должно выводиться сообщение: "Баланс не может быть отрицательным"
# Локация дефекта
https://github.com/Sushnyak/commProject/blob/a8e7b11041b36543c475491c2c0a9dbddcceae30/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L19
# Шаги воспроизведения
1. Открыть код программы в IDEA
2. Создать объект класса CreditAccount со значениями: начальный баланс = -1000, кредитный лимит = 5.000, ставка кредитования = 15
3. Запустить программу
Ожидаемый результат: выкидывается исключение вида IllegalArgumentException.
Фактический результат: начальному балансу присвоено значение "-1000"
# Скриншот
![image](https://github.com/Sushnyak/commProject/assets/124073086/64a819ee-d3ff-4df6-bc8a-8891bfcd4d61)
# Окружение 
* **Операционная система:** Windows 10
* **IDE:** intellij IDEA Communiti Edition 2024.1.1
* **Java:** Open JDK 11

**Comment by MariaGamzina** [comment]
добавлено исключение для отрицательного баланса
