### ISSUE TITLE
При вводе некорректного кредитного лимита должно выкидываться исключение

### ISSUE THREAD

**Issue by Sushnyak** [Sushnyak/commProject#2]
# Описание
При попытке присвоить отрицательный кредитный лимит, должно выводиться сообщение: "Кредитный лимит не может быть отрицательным"
# Локация дефекта
https://github.com/Sushnyak/commProject/blob/a8e7b11041b36543c475491c2c0a9dbddcceae30/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L19
# Шаги воспроизведения
1. Открыть код программы в IDEA
2. Создать объект класса CreditAccount со значениями: начальный баланс = 0, кредитный лимит = -5.000, ставка кредитования = 15
3. Запустить программу
Ожидаемый результат: выкидывается исключение вида IllegalArgumentException.
Фактический результат: кредитному лимиту присвоено значение "-5000"
# Скриншот
![image](https://github.com/Sushnyak/commProject/assets/124073086/aee023b8-cd83-45a9-bd40-637353ed0034)
# Окружение 
* **Операционная система:** Windows 10
* **IDE:** intellij IDEA Communiti Edition 2024.1.1
* **Java:** Open JDK 11

**Comment by MariaGamzina** [comment]
добавлено исключение для отрицательного кредитного лимита
