### ISSUE TITLE
Не верно отображается баланс после оплаты

### ISSUE THREAD

**Issue by Sushnyak** [Sushnyak/commProject#3]
# Описание
Не верно считается баланс после оплаты
# Локация дефекта
https://github.com/Sushnyak/commProject/blob/a8e7b11041b36543c475491c2c0a9dbddcceae30/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L45-L47
# Шаги воспроизведения
1. Открыть код программы в IDEA
2. Создать объект класса CreditAccount со значениями: начальный баланс = 0, кредитный лимит = 5.000, ставка кредитования = 15
3. Присвоить балансу значение: 3.000 (account.add(3_000);)
4. Уменьшить баланс на 1.000 (account.pay(1_000);)
Ожидаемый результат: баланс равен 2.000
Фактический результат: баланс равен -1.000
# Скриншот
![image](https://github.com/Sushnyak/commProject/assets/124073086/a1362d0b-384e-4bee-98f9-d239ed7392c6)
# Окружение 
* **Операционная система:** Windows 10
* **IDE:** intellij IDEA Communiti Edition 2024.1.1
* **Java:** Open JDK 11

**Comment by MariaGamzina** [comment]
исправлено
