### ISSUE TITLE
Не верно считается баланс после оплаты, при превышении кредитного лимита

### ISSUE THREAD

**Issue by Sushnyak** [Sushnyak/commProject#4]
# Описание
Не верно считается баланс после оплаты, при превышении кредитного лимита 
# Локация дефекта
https://github.com/Sushnyak/commProject/blob/a8e7b11041b36543c475491c2c0a9dbddcceae30/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L45-L47
# Шаги воспроизведения
1. Открыть код программы в IDEA
2. Создать объект класса CreditAccount со значениями: начальный баланс = 0, кредитный лимит = 100, ставка кредитования = 15
3. Присвоить балансу значение: 3.000 (account.add(3_000);)
4. Уменьшить баланс на 4.000 (account.pay(4_000);)
Ожидаемый результат: баланс не изменился, т.к. сумма покупки превышает баланс и кредитный лимит
Фактический результат: баланс равен -1.000
# Скриншот
![image](https://github.com/Sushnyak/commProject/assets/124073086/6a938229-3b54-4fad-914d-8d8389448e18)
# Окружение 
* **Операционная система:** Windows 10
* **IDE:** intellij IDEA Communiti Edition 2024.1.1
* **Java:** Open JDK 11

**Comment by MariaGamzina** [comment]
исправлено
