### ISSUE TITLE
Проценты не должны начитсяться если баланс положительный

### ISSUE THREAD

**Issue by Sushnyak** [Sushnyak/commProject#5]
# Описание
Проценты не должны начитсяться если баланс положительный
# Локация дефекта
https://github.com/Sushnyak/commProject/blob/a8e7b11041b36543c475491c2c0a9dbddcceae30/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L82-L84
# Шаги воспроизведения
1. Открыть код программы в IDEA
2. Создать объект класса CreditAccount со значениями: начальный баланс = 100, кредитный лимит = 0, ставка кредитования = 15
3. Вызвать функцию начисления процентов (account.yearChange())
Ожидаемый результат: проценты не начислятся, т.к. баланс положительный
Фактический результат: сумма процентов составляет 15 рублей
# Скриншот
![image](https://github.com/Sushnyak/commProject/assets/124073086/e6601305-261d-4fc2-b5ac-e1245bcff24b)
# Окружение 
* **Операционная система:** Windows 10
* **IDE:** intellij IDEA Communiti Edition 2024.1.1
* **Java:** Open JDK 11

**Comment by MariaGamzina** [comment]
добавлено условие, что при положительном балансе ответ 0
