### ISSUE TITLE
При пополнении сберегательного счета на балансе должна отображаться сумма начального баланса и пополнения

### ISSUE THREAD

**Issue by MariaGamzina** [Sushnyak/commProject#6]
#Описание
При пополнении сберегательного счета на балансе отображается только сумма пополнения без учета начального баланса 

#Локация дефекта
https://github.com/Sushnyak/commProject/blob/a8e7b11041b36543c475491c2c0a9dbddcceae30/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L68

#Шаги воспроизведения

1. Открыть [код программы](https://github.com/Sushnyak/commProject/blob/main/src/main/java/ru/netology/javaqadiplom/SavingAccount.java) в IDEA
2. Создать объект класса SavingAccount (начальный баланс 2000, минимальный баланс 1000, максимальный баланс 10000, ставка 5)
3. Методом add пополнить баланс на 3000: account.add(3_000);
4. Запустить программу

*Ожидаемый результат:* Баланс равен 5000.
*Фактический результат:* Баланс равен 3000.

#Скриншот
![пополнение](https://github.com/Sushnyak/commProject/assets/161510162/6477e528-51b2-4fdd-8df2-93fdeff2317b)

#Окружение
* **Операционная система:**Windows 11 Pro 22H2
* **IDE:**IntelliJ IDEA 2023.3.6 (Ultimate Edition)
* **Java:**OpenJDK11

**Comment by Sushnyak** [comment]
Теперь после пополнения сбер.счета отображается баланс, с учетом баланса до пополнения.
Теперь если после пополнения баланс превышает максимальный, выкидывается исключение.
