### ISSUE TITLE
При вводе максимального баланса меньше минимального баланса должно выкидываться исключение

### ISSUE THREAD

**Issue by MariaGamzina** [Sushnyak/commProject#7]
#Описание
При вводе максимального баланса меньше минимального баланса должно выкидываться исключение 

#Локация дефекта
https://github.com/Sushnyak/commProject/blob/a8e7b11041b36543c475491c2c0a9dbddcceae30/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L22

#Шаги воспроизведения

1. Открыть [код программы](https://github.com/Sushnyak/commProject/blob/main/src/main/java/ru/netology/javaqadiplom/SavingAccount.java) в IDEA
2. Создать объект класса SavingAccount (начальный баланс 6000, минимальный баланс 5000, максимальный баланс 2000, ставка 2)
3. Запустить программу

*Ожидаемый результат:* Выкидывается исключение класса IllegalArgumentException.
*Фактический результат:* Исключение не найдено.

#Скриншот
![исключение](https://github.com/Sushnyak/commProject/assets/161510162/8c24205b-70a8-4e22-884e-87a8983351de)

#Окружение
* **Операционная система:**Windows 11 Pro 22H2
* **IDE:**IntelliJ IDEA 2023.3.6 (Ultimate Edition)
* **Java:**OpenJDK11

**Comment by Sushnyak** [comment]
Теперь если минимальный баланс превышает максимальный баланс, то выкидывается исключение.
