### ISSUE TITLE
При вводе начального баланса меньше минимального баланса должно выкидываться исключение 

### ISSUE THREAD

**Issue by MariaGamzina** [Sushnyak/commProject#8]
#Описание
При вводе начального баланса меньше минимального баланса должно выкидываться исключение 

#Локация дефекта
https://github.com/Sushnyak/commProject/blob/a8e7b11041b36543c475491c2c0a9dbddcceae30/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L22

#Шаги воспроизведения

1. Открыть [код программы](https://github.com/Sushnyak/commProject/blob/main/src/main/java/ru/netology/javaqadiplom/SavingAccount.java) в IDEA
2. Создать объект класса SavingAccount (начальный баланс 1999, минимальный баланс 2000, максимальный баланс 10000, ставка 2)
3. Запустить программу

*Ожидаемый результат:* Выкидывается исключение класса IllegalArgumentException.
*Фактический результат:* Исключение не найдено.

#Скриншот

![исключ2](https://github.com/Sushnyak/commProject/assets/161510162/dc3346c5-e8f4-4047-8465-3659236d58ef)

#Окружение
* **Операционная система:**Windows 11 Pro 22H2
* **IDE:**IntelliJ IDEA 2023.3.6 (Ultimate Edition)
* **Java:**OpenJDK11

**Comment by Sushnyak** [comment]
Теперь если начальный баланс меньше минимального баланса, то выкидывается исключение.
