### ISSUE TITLE
При списании средств со сберегательного счета баланс становится меньше минимального баланса

### ISSUE THREAD

**Issue by MariaGamzina** [Sushnyak/commProject#9]
#Описание
При списании средств со сберегательного счета баланс становится меньше минимально допустимого баланса 

#Локация дефекта
https://github.com/Sushnyak/commProject/blob/a8e7b11041b36543c475491c2c0a9dbddcceae30/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L44

#Шаги воспроизведения

1. Открыть [код программы](https://github.com/Sushnyak/commProject/blob/main/src/main/java/ru/netology/javaqadiplom/SavingAccount.java) в IDEA
2. Создать объект класса SavingAccount (начальный баланс 2000, минимальный баланс 1000, максимальный баланс 10000, ставка 5)
3. Методом pay списать средства -1001: account.pay(1_001);
4. Запустить программу

*Ожидаемый результат:* Баланс равен 2000.
*Фактический результат:* Баланс равен 999.

#Скриншот
![списание](https://github.com/Sushnyak/commProject/assets/161510162/9d01e779-f56e-408d-b1aa-44fd0428d472)

#Окружение
* **Операционная система:**Windows 11 Pro 22H2
* **IDE:**IntelliJ IDEA 2023.3.6 (Ultimate Edition)
* **Java:**OpenJDK11

**Comment by Sushnyak** [comment]
Теперь если уменьшение баланса приведет к значению ниже разрешенного, то операция не пройдет и баланс не уменьшится
